# Generated by Django 6.0.1 on 2026-01-08 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('term', models.CharField(blank=True, max_length=20, verbose_name='Período')),
                ('status', models.CharField(choices=[('CURSANDO', 'Cursando'), ('CONCLUIDA', 'Concluída')], default='CURSANDO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('class_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número da aula')),
                ('date', models.DateField(verbose_name='Data')),
                ('watched', models.BooleanField(default=False, verbose_name='Assistida')),
                ('reviewed_p1', models.BooleanField(default=False, verbose_name='Revisada P1')),
                ('reviewed_p2', models.BooleanField(default=False, verbose_name='Revisada P2')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.course')),
            ],
            options={
                'ordering': ['date', 'class_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.course')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('type', models.CharField(choices=[('LISTA', 'Lista/Exercícios'), ('TRABALHO', 'Trabalho'), ('LEITURA', 'Leitura'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo')),
                ('good_by', models.DateField(blank=True, null=True, verbose_name='Bom para')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Entrega')),
                ('status', models.CharField(choices=[('TODO', 'A fazer'), ('DOING', 'Fazendo'), ('DONE', 'Concluída')], default='TODO', max_length=10, verbose_name='Status')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.course')),
            ],
            options={
                'ordering': ['status', 'due_date', 'good_by', 'title'],
            },
        ),
    ]
