# Generated by Django 6.0.1 on 2026-01-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Questão')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Tema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.course')),
            ],
            options={
                'ordering': ['course', 'topic', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='Acertou?')),
                ('time_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo (segundos)')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.question')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
