# Generated by Django 6.0.1 on 2026-01-25 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_questionattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Alternativa')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correta?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
            options={
                'ordering': ['question', 'id'],
            },
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='core.questionoption'),
        ),
    ]
