# Generated by Django 6.0.1 on 2026-01-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionoption_questionattempt_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resolution',
            field=models.TextField(blank=True, verbose_name='Resolução'),
        ),
    ]
