# Generated by Django 6.0.1 on 2026-02-08 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_profile_wizard_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=120, verbose_name='Instituição')),
                ('prova_nome', models.CharField(max_length=120, verbose_name='Prova')),
                ('ano', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='study/sources/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ano', 'instituicao', 'prova_nome'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('choice_a', models.CharField(max_length=240, verbose_name='Alternativa A')),
                ('choice_b', models.CharField(max_length=240, verbose_name='Alternativa B')),
                ('choice_c', models.CharField(max_length=240, verbose_name='Alternativa C')),
                ('choice_d', models.CharField(max_length=240, verbose_name='Alternativa D')),
                ('choice_e', models.CharField(max_length=240, verbose_name='Alternativa E')),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Correta')),
                ('explanation', models.TextField(blank=True, verbose_name='Comentário')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Média'), ('HARD', 'Difícil')], default='MEDIUM', max_length=10, verbose_name='Dificuldade')),
                ('source_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Página')),
                ('source_snippet', models.CharField(blank=True, max_length=200, verbose_name='Trecho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='study.studyplan')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='study.studysource')),
            ],
            options={
                'ordering': ['tag__area', 'tag__tema', 'tag__subtema', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('BLOCK', 'Bloco'), ('REVIEW', 'Revisão')], default='BLOCK', max_length=10, verbose_name='Modo')),
                ('planned_questions', models.PositiveIntegerField(verbose_name='Questões planejadas')),
                ('target_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo alvo (min)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='study.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Ordem')),
                ('user_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Resposta')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Acertou?')),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo (segundos)')),
                ('flagged_review', models.BooleanField(default=False, verbose_name='Revisar depois')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_items', to='study.studyquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='study.studysession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'order'), ('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='StudyErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_reason', models.CharField(choices=[('CONTEUDO', 'Conteúdo'), ('INTERPRETACAO', 'Interpretação'), ('PEGADINHA', 'Pegadinha'), ('PRESSA', 'Pressa'), ('ESQUECI_REGRA', 'Esqueci regra'), ('CONFUSAO_DIAG', 'Confusão diagnóstica'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Motivo')),
                ('rule_of_thumb', models.CharField(max_length=200, verbose_name='Regra de bolso')),
                ('note', models.CharField(blank=True, max_length=280, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_error_logs', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='study.studyquestion')),
                ('session_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='study.studysessionitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=80, verbose_name='Área')),
                ('tema', models.CharField(max_length=80, verbose_name='Tema')),
                ('subtema', models.CharField(max_length=80, verbose_name='Subtema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['area', 'tema', 'subtema'],
                'unique_together': {('area', 'tema', 'subtema')},
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='recommended_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_sessions', to='study.studytag'),
        ),
        migrations.AddField(
            model_name='studyquestion',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='study.studytag'),
        ),
        migrations.CreateModel(
            name='StudyReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(1, '24h'), (2, '7d'), (3, '30d')], default=1, verbose_name='Etapa')),
                ('due_at', models.DateTimeField(verbose_name='Vence em')),
                ('last_result', models.CharField(blank=True, choices=[('CORRECT', 'Acerto'), ('INCORRECT', 'Erro')], max_length=10, verbose_name='Último resultado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to='study.studyquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['user', 'active', 'due_at'], name='study_study_user_id_ef164e_idx'), models.Index(fields=['question', 'active'], name='study_study_questio_9b47f3_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
