# Generated by Django 6.0.1 on 2026-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_game', '0002_activity_completion_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycompletionlog',
            name='kind',
            field=models.CharField(choices=[('CLASS_WATCHED', 'Aula assistida'), ('REVIEW_P1', 'Revisão P1'), ('REVIEW_P2', 'Revisão P2'), ('STUDY_SESSION', 'Sessão de estudo'), ('STUDY_REVIEW', 'Revisão de estudo')], max_length=30),
        ),
    ]
